# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4

      # Runs a single command using the runners shell
      #- name: Stop all docker containers
      #  run: docker stop $(docker ps -a -q)

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo rm -f -r '/etc/repos/nginx'
          cd /etc/repos/
          sudo git clone https://github.com/dannyatcornellconsulting/nginx.git
          #sudo docker stop $(docker ps -a -q)
          #sudo docker rm $(docker ps -a -q)
          sudo rm -f -r '/etc/docker/nginx'
          sudo mkdir '/etc/docker/nginx'
          cp '/etc/repos/nginx/index.html' '/etc/docker/nginx/index.html'
          cp '/etc/repos/nginx/Dockerfile' '/etc/docker/nginx/Dockerfile'
          cd '/etc/docker/nginx/'
          sudo docker build -t nginx .
          sudo docker run --name nginxweb1 -p 8080:80 nginx
